- hosts: localhost

  tasks:
    - import_tasks: tasks/ssh.yml
      tags:
        - install
        - dotfiles
        - ssh

    - import_tasks: tasks/git.yml
      tags:
        - install
        - dotfiles

    - import_tasks: tasks/fish.yml
      tags:
        - install
        - dotfiles
        - fish

    - import_tasks: tasks/dotfiles.yml
      tags:
        - install
        - dotfiles
        - stow

    - import_tasks: tasks/font.yml
      tags:
        - install
        - dotfiles
        - font

    - import_tasks: tasks/npm.yml
      become: yes
      tags:
        - install
        - npm

    - import_tasks: tasks/packages.yml

    # TODO
    # - include_tasks: tasks/nvim.yml

    # - include_tasks: tasks/brave.yml

    # - include_tasks: tasks/slack.yml
