- hosts: localhost
  vars:
    HOME: "{{ lookup('env', 'HOME') }}"
    USER: "{{ lookup('env', 'USER') }}"

  tasks:
    - import_tasks: tasks/00-core.yml
    - import_tasks: tasks/01-git.yml
    - import_tasks: tasks/02-fish.yml
    - import_tasks: tasks/03-dotfiles.yml
    - import_tasks: tasks/04-font.yml
    - import_tasks: tasks/05-npm.yml
    - import_tasks: tasks/06-wm.yml

    # TODO
    # - include_tasks: tasks/nvim.yml
    # - include_tasks: tasks/brave.yml
    # - include_tasks: tasks/slack.yml

    - import_tasks: tasks/99-japanese.yml
