- hosts: localhost
  vars:
    HOME: "{{ lookup('env', 'HOME') }}"
    USER: "{{ lookup('env', 'USER') }}"

  tasks:
    - import_tasks: tasks/01-ssh.yml
    - import_tasks: tasks/02-git.yml
    - import_tasks: tasks/03-packages.yml
    - import_tasks: tasks/04-fish.yml
    - import_tasks: tasks/05-dotfiles.yml
    - import_tasks: tasks/06-font.yml
    - import_tasks: tasks/07-npm.yml

    # TODO
    # - include_tasks: tasks/nvim.yml
    # - include_tasks: tasks/brave.yml
    # - include_tasks: tasks/slack.yml

    - import_tasks: tasks/99-japanese.yml
