- hosts: localhost
  vars:
    HOME: "{{ lookup('env', 'HOME') }}"
    USER: "{{ lookup('env', 'USER') }}"

  become: yes
  tasks:
    - import_tasks: tasks/01-ssh.yml
      tags:
        - dotfiles
        - ssh
    - import_tasks: tasks/02-git.yml
      tags:
        - dotfiles
    - import_tasks: tasks/03-packages.yml
      tags:
        - dotfiles
        - cli
    - import_tasks: tasks/04-fish.yml
      tags:
        - dotfiles
        - fish
    - import_tasks: tasks/05-dotfiles.yml
      tags:
        - dotfiles
        - stow
    - import_tasks: tasks/06-font.yml
      tags:
        - dotfiles
        - font
    - import_tasks: tasks/07-npm.yml
      tags:
        - npm
    - import_tasks: tasks/08-japanese.yml
      tags:
        - japanese

    # TODO
    # - include_tasks: tasks/nvim.yml
    # - include_tasks: tasks/brave.yml
    # - include_tasks: tasks/slack.yml
