- name: Install core pacman pkgs
  become: yes
  tags:
    - core
    - dotfiles
  when: ansible_facts['distribution'] == "Archlinux"
  pacman:
    state: present
    name:
      - curl
      - bat
      - btop
      - exa
      - fd
      - fish
      - fzf
      - gcr
      - gnome-keyring
      - lazygit
      - libsecret
      - neofetch
      - seahorse
      - stow
      - powertop

# Debian based Install
- name: Install core apt pkgs
  tags:
    - core
    - dotfiles
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: Install apt pkgs
      become: yes
      apt:
        state: present
        name:
          - curl
          - bat
          - btop
          - exa
          - fd-find
          - fish
          - fzf
          - gcr
          - gnome-keyring
          - libsecret
          - neofetch
          - seahorse
          - stow
          - powertop

    # Turn fd-find into fd
    - name: Create ~/.local/bin directory
      file:
        path: "{{ HOME }}/.local/bin"
        state: directory
        mode: 0755

    - name: Create Symlink for fd
      file:
        src: /usr/bin/fdfind
        dest: "{{ HOME }}/.local/bin/fd"
        state: link
        force: yes

    # Install lazygit binary
    - name: Install lazygit
      shell: "./scripts/lazygit.sh"
