- name: Set up and stow Dotfiles
  tags:
    - dotfiles
  block:
    - name: Clone .dotfiles
      git:
        repo: "git@github.com:OrangeRed/.dotfiles.git"
        dest: "{{ HOME }}/.dotfiles"
        version: main
        force: yes
        accept_hostkey: yes

    - name: Stow dotfiles
      shell: |
        cd ~/.dotfiles
        stow --adopt -t ~/ .wallpapers/
        stow --adopt -t ~/ btop/
        stow --adopt -t ~/ env.d/
        stow --adopt -t ~/ fd/
        stow --adopt -t ~/ fish/
        stow --adopt -t ~/ neofetch/
        stow --adopt -t ~/ ranger/
        stow --adopt -t ~/ vscode/
        git reset --hard

    - name: Source fish envs
      shell: fish -c "source ~/.dotfiles/fish/.config/fish/conf.d/envs.fish"
