- name: Install pacman pkgs
  become: yes
  tags:
    - cli
    - dotfiles
  when: ansible_facts['distribution'] == "Archlinux"
  pacman:
    state: present
    name:
      - cmatrix
      - bat
      - btop
      - exa
      - fd
      - fish
      - fzf
      - lazygit
      - neofetch
      - stow
      - powertop

# Debian based Install
- name: Install api pkgs
  tags:
    - cli
    - dotfiles
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: Install apt pkgs
      become: yes
      apt:
        state: present
        name:
          - cmatrix
          - bat
          - btop
          - exa
          - fd-find # fd is taken
          - fish
          - fzf
          - neofetch
          - stow
          - powertop
          - xclip

    # Turn fd-find into fd
    - name: Create ~/.local/bin directory
      file:
        path: "{{ HOME }}/.local/bin"
        state: directory
        mode: 0755

    - name: Create Symlink for fd
      file:
        src: /usr/bin/fdfind
        dest: "{{ HOME }}/.local/bin/fd"
        state: link
        force: yes

    # Install lazygit binary
    - name: Install lazygit
      shell: "./scripts/lazygit.sh"
