- name: Download font and update cache
  tags:
    - font
    - dotfiles
  block:
    - name: Create ~/.fonts directory
      file:
        path: "{{ HOME }}/.fonts"
        state: directory
        mode: 0755

    - name: Get Latest Monaspace font
      uri:
        url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
        return_content: true
      register: res

    - name: Download Fira Code font
      unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ res.json.tag_name }}/FiraCode.zip"
        dest: "{{ HOME }}/.fonts"
        remote_src: yes

    - name: Update font cache
      become: yes
      shell: fc-cache -fv
