- name: Install Node and global npm packages
  tags:
    - npm
  block:
    - name: Install Node
      become: yes
      package:
        name:
          - nodejs
          - npm
        state: present

    - name: Install pnpm
      become: yes
      npm:
        name: pnpm
        global: yes
