- name: Install Japanese stuff
  tags:
    - japanese
  when: ansible_facts['distribution'] == "Archlinux"
  block:
    - name: Install anki, mpv, fcitx5
      become: yes
      pacman:
        state: present
        name:
          # - anki-bin
          - mpv
          - fcitx5-mozc
          - fcitx5-configtool

    - name: Install mpvacious
      git:
        repo: https://github.com/Ajatt-Tools/mpvacious.git
        dest: "{{ HOME }}/.config/mpv/scripts/subs2srs"
        force: yes
        accept_hostkey: yes

    - name: Stow dotfiles
      shell: |
        cd ~/.dotfiles
        stow --adopt -t ~/ fcitx5/
        stow --adopt -t ~/ mpv/
        git reset --hard
