- name: Install command line tools
  become: yes
  package:
    state: present
    name:
      - cmatrix
      - bat
      - btop
      - fd
      - fzf
      - lazygit
      - neofetch
      - powertop
