- name: Clone .dotfiles
  git:
    repo: "git@github.com:OrangeRed/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    version: main
    force: yes
    update: yes
    # recursive: yes
    accept_hostkey: yes

- name: Install stow
  package:
    state: present
    name: stow

- name: Stow dotfiles
  shell: |
    cd $HOME/.dotfiles
    stow -t $HOME */ --adopt
    git reset --hard
