- name: Clone .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:OrangeRed/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    version: main
    force: yes
    update: yes
    recursive: yes
    accept_hostkey: yes
  tags: &tags_for_dotfile_tasks ["dotfiles", "install", "stow"]

- name: Install stow
  package:
    state: present
    name: stow
  tags: *tags_for_dotfile_tasks

- name: Stow and adopt dotfiles
  shell: |
    cd $HOME/.dotfiles
    stow -t $HOME */ --adopt
  tags: *tags_for_dotfile_tasks

- name: Reset adoption but keep symlinks
  shell: |
    cd $HOME/.dotfiles
    git reset --hard
  tags: *tags_for_dotfile_tasks
