- name: Installing stow
  package:
    state: present
    name: stow
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:OrangeRed/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: |
    cd $HOME/.dotfiles
    stow -t $HOME */
  tags:
    - install
    - dotfiles
    - stow
