- name: Clone .dotfiles
  git:
    repo: "git@github.com:OrangeRed/.dotfiles.git"
    dest: "{{ HOME }}/.dotfiles"
    version: main
    force: yes
    accept_hostkey: yes

- name: Install stow
  package:
    state: present
    name: stow

- name: Stow dotfiles
  shell: |
    cd ~/.dotfiles
    stow -t ~/ */ --adopt
    git reset --hard
