- name: Install Fish shell package
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  package:
    name: fish
    state: present
  tags: &tags_for_fish_tasks ["install", "productivity", "dotfiles", "fish"]

- name: make the fisher directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/functions"
    owner: "{{ lookup('env', 'USER') }}"
    mode: 0755
    state: directory
    recurse: yes
  tags: *tags_for_fish_tasks

- name: Install Fisher
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  get_url: 
    url="https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish"
    dest="{{ lookup('env', 'HOME') }}/.config/fish/functions"
  tags: *tags_for_fish_tasks

- name: Install Fisher Plugins
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  shell: fish -c "fisher install danhper/fish-ssh-agent jorgebucaran/nvm.fish jethrokuan/z"
  tags: *tags_for_fish_tasks

- name: Remove Fish Greeting
  shell: fish -c "set -U fish_greeting"
  tags: *tags_for_fish_tasks

- name: Change shell to fish
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/fish
  tags: *tags_for_fish_tasks
