- name: Install pnpm
  npm:
    name: pnpm
    global: yes

- name: Install eslint
  npm:
    name: eslint
    global: yes

- name: Install Typescript
  npm:
    name: typescript
    global: yes

- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
